DROP TYPE IF EXISTS race CASCADE;

DROP TYPE IF EXISTS char_class CASCADE;

DROP TYPE IF EXISTS sub_class CASCADE;

DROP TABLE IF EXISTS stickers CASCADE;

DROP TABLE IF EXISTS feature_pack CASCADE;

DROP TABLE IF EXISTS equipment_pack CASCADE;

DROP TABLE IF EXISTS party CASCADE;

DROP TABLE IF EXISTS characters CASCADE;

DROP TABLE IF EXISTS users CASCADE;
